name: 'Publish docs to GitHub Pages'
description: 'Action that publishes docs to the ghpages branch'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node16'
  main: 'dist/index.js'
